[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 12.5

[font.bold]
family = "0xProto Nerd Font"
style = "Bold"

[font.bold_italic]
family = "0xProto Nerd Font"
style = "Bold Italic"

[font.italic]
family = "0xProto Nerd Font"
style = "Italic"

[font.normal]
family = "0xProto Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 1

[scrolling]
history = 5000

[window]
dynamic_padding = false
opacity = 0.9
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 0
y = 0

